### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by wako-mori** [wako-mori/chat-space#9]
# IPアドレス
3.114.136.22

**Comment by yasunamiura** [comment]
須藤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①非同期・自動更新時に画像が揃うようにしましょう**
<img width="1422" alt="ChatSpace_と_ChatSpace-2" src="https://user-images.githubusercontent.com/52514431/80048431-218ab000-854b-11ea-8e44-e19238ac14c7.png">

**②新規グループ作成をして１回目のメッセージ送信でも自動更新が行われるようにしましょう**
<img width="1425" alt="ChatSpace_と_ChatSpace" src="https://user-images.githubusercontent.com/52514431/80048477-4121d880-854b-11ea-9535-18cf6fe658d3.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by wako-mori** [comment]
上記内容を修正しました。
再度、ご確認をお願いいたします。

**Comment by yasunamiura** [comment]
さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の修正を確認できました！新たに以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①ビューが大きく崩れている**
[![Image from Gyazo](https://i.gyazo.com/7c0a9aca85c1f6d98d89aa259930a723.gif)](https://gyazo.com/7c0a9aca85c1f6d98d89aa259930a723)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by wako-mori** [comment]
ご確認いただき、ありがとうございます。
ご指摘いただいたビュー崩れですが、私のPCでは特にビュー崩れの確認ができない状況です。
PCによってビュー崩れが発生する場合もありますでしょうか。
また、その場合の修正ポイントなどはありますでしょうか。
お手数をおかけし申し訳ございません。

https://gyazo.com/cc56e646655f6d97296dfbb24472b831

**Comment by yasunamiura** [comment]
>PCによってビュー崩れが発生する場合もありますでしょうか。
はい、解像度の違いで崩れてしまう場合がございます。

こちらは動作確認のみお返事していますので、以上のこととコネクトにてご質問いただきメンターにお伝えしていただいてもよろしいでしょうか？

**Comment by wako-mori** [comment]
ご確認ありがとうございます。
メンターさんに確認したところ、閲覧環境を聞いた上で、それに適した修正を行った方が良いと言われました。
お手数ですが、閲覧環境を教えていただけないでしょうか。
私の方で確認した内容は下記の通りです。
【確認項目】
MacBook　Pro
・Google　Chrome
・Safari
・Responsive Viewer（ツール）iPone,ギャラクシー画面の確認

お手数をおかけし申し訳ございません。
よろしくお願いいたします。

**Comment by yasunamiura** [comment]
ご質問ありがとうございます！
こちらの閲覧環境を再度確認させていただいたところ
Chromeの画面拡大数が75%になっておりこれにより画面が崩れたように見えていました。
アプリに全く問題はございませんでした。
ご多用の中、何度も確認のお時間いただき大変申し訳ありませんでした。
<img width="1342" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/80164823-04baaf00-8615-11ea-825f-a960516a5fd5.png">

修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
